name: Build and push images to Quay.io registry
on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 1 * * 3'

jobs:
  build-and-push:
    if: github.repository_owner == 'sclorg'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: "8.0/Dockerfile.c9s"
            registry_namespace: "sclorg"
            tag: "c9s"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            image_name: "mysql-80-c9s"
          - dockerfile: "8.0/Dockerfile.c8s"
            registry_namespace: "sclorg"
            tag: "c8s"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            image_name: "mysql-80-c8s"
          - dockerfile: "8.0/Dockerfile.fedora"
            registry_namespace: "fedora"
            tag: "80"
            quayio_username: "QUAY_IMAGE_FEDORA_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_FEDORA_BUILDER_TOKEN"
            image_name: "mysql-80"
    steps:
      - name: Build and push to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ secrets[matrix.quayio_username] }}
          registry_token: ${{ secrets[matrix.quayio_token] }}
          dockerfile: ${{ matrix.dockerfile }}
          tag: ${{ matrix.tag }}
          image_name: ${{ matrix.image_name }}
