name: Build and push images to Quay.io registry
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "8.0"
            dockerfile: "Dockerfile"
            registry_namespace: "centos7"
            tag: "centos7"
          - version: "8.0"
            dockerfile: "Dockerfile.c9s"
            registry_namespace: "sclorg"
            tag: "c9s"

    steps:
      - uses: actions/checkout@v2

      - name: Get base image name
        id: base-image-name
        run: |
          # This command returns row with BASE_IMAGE_NAME
          row=$(grep "BASE_IMAGE_NAME" Makefile)
          # Return only base image name
          BASE_IMAGE_ROW=${row/BASE_IMAGE_NAME = /}
          echo ::set-output name=image_name::$BASE_IMAGE_ROW

      - name: Get short version
        id: short_version
        run: |
          ver="${{ matrix.version }}"
          echo "::set-output name=SHORT_VER::${ver//./}"

      - name: Login to Quay.io private registry
        if: ${{ matrix.registry_namespace == 'sclorg' }}
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_TOKEN }}

      - name: Check if .exclude-${{ matrix.tag }} is present in version directory
        id: check_exclude_file
        # https://github.com/marketplace/actions/file-existence
        uses: andstor/file-existence-action@v1
        with:
          files: "${{ matrix.version }}/.exclude-${{ matrix.tag }}"

      - name: Build image
        if: steps.check_exclude_file.outputs.files_exists == 'false'
        id: build-image
        # https://github.com/marketplace/actions/buildah-build
        uses: redhat-actions/buildah-build@v2
        with:
          dockerfiles: ${{ matrix.version }}/${{ matrix.dockerfile }}
          image: ${{ steps.base-image-name.outputs.image_name}}-${{ steps.short_version.outputs.SHORT_VER }}-${{ matrix.tag }}
          tags: latest ${{ matrix.tag }} ${{ github.sha }}

      - name: Push image to Quay.io/${{ matrix.registry_namespace }} namespace
        if: ${{ steps.check_exclude_file.outputs.files_exists == 'false' && matrix.registry_namespace == 'centos7' }}
        id: push-to-quay-centos7
        uses: redhat-actions/push-to-registry@v2.2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/${{ matrix.registry_namespace }}
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}

      - name: Push image to Quay.io/${{ matrix.registry_namespace }} namespace
        if: ${{ steps.check_exclude_file.outputs.files_exists == 'false' && matrix.registry_namespace == 'sclorg' }}
        id: push-to-quay-sclorg
        uses: redhat-actions/push-to-registry@v2.2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/${{ matrix.registry_namespace }}
          username: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_SCLORG_BUILDER_TOKEN  }}

      - name: Print image url
        if: ${{ matrix.registry_namespace == 'centos7' }}
        run: echo "Image pushed to ${{ steps.push-to-quay-centos7.outputs.registry-paths }}"

      - name: Print image url
        if: ${{ matrix.registry_namespace == 'sclorg' }}
        run: echo "Image pushed to ${{ steps.push-to-quay-sclorg.outputs.registry-paths }}"
